# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 5 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: 
markdown: kramdown
title: Kadir Burak's Cyber Security blog

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Kadir Burak's Cyber Security blog

description: Personal blog of Kadir Burak Mavzer
author:
  name: Kadir Burak
  email: mavzer122@gmail.com
  github: mavzerburak0
  linkedin: kadirburakmavzer
  bio: Hello! I am a cloud security engineer, focused on GCP and AWS security.
  email_md5: f738f728300835bb12c636a85fc1d2c7

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html


BASE_PATH:

plugins:
  - jekyll-paginate
  - jekyll-feed
