# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 5 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: 
markdown: kramdown
title: Burak's Cyber Security blog

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Burak's Cyber Security blog

description: Personal blog of Burak Mavzer
author:
  name: Burak
  email: mavzer122@gmail.com
  github: mavzerburak0
  linkedin: kadir-burak-mavzer
  bio: Hello! I'm a recent graduate of Cyber Security Engineering from Tallinn University of Technology. Currently working at VisionSpace Technologies GmbH @ Darmstadt, Germany.
  email_md5: f738f728300835bb12c636a85fc1d2c7

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html


BASE_PATH:

plugins:
  - jekyll-paginate
  - jekyll-feed
